# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-31 19:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=18, null=True)),
                ('website', models.CharField(blank=True, max_length=400, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('skype', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/user/')),
                ('join_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Automated_Webinar_Funnel_Version_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default='Automated Webinar Funnel Version 1', max_length=100, null=True)),
                ('visitors', models.IntegerField(blank=True, default=0, null=True)),
                ('leads', models.IntegerField(blank=True, default=0, null=True)),
                ('conversion_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('campaign_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Automated_Webinar_Funnel_Version_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default='Automated Webinar Funnel Version 2', max_length=100, null=True)),
                ('visitors', models.IntegerField(blank=True, default=0, null=True)),
                ('leads', models.IntegerField(blank=True, default=0, null=True)),
                ('conversion_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('campaign_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user4', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AweberAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aweber_username', models.CharField(blank=True, max_length=100, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BeTheMillionaire_3_Step_Registration_Funnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default='BeTheMillionaire 3-Step Registration Funnel', max_length=100, null=True)),
                ('visitors', models.IntegerField(blank=True, default=0, null=True)),
                ('leads', models.IntegerField(blank=True, default=0, null=True)),
                ('conversion_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('campaign_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bitconnect_Direct_Funnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default='Bitconnect Direct Funnel', max_length=100, null=True)),
                ('visitors', models.IntegerField(blank=True, default=0, null=True)),
                ('leads', models.IntegerField(blank=True, default=0, null=True)),
                ('conversion_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('campaign_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user11', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BitconnectAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitconnect_username', models.CharField(blank=True, max_length=100, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BitPandaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitpanda_username', models.CharField(blank=True, max_length=100, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CexIOAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cexio_username', models.CharField(blank=True, max_length=100, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClickFunnelsAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clickfunnels_username', models.CharField(blank=True, max_length=100, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClickMagicAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clickmagic_username', models.CharField(blank=True, max_length=100, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoinBaseAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinbase_username', models.CharField(blank=True, max_length=100, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoinMamaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_mama_username', models.CharField(blank=True, max_length=100, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Giveaway_3_Steps_Funnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default='Course Giveaway 3 Steps Funnel', max_length=100, null=True)),
                ('visitors', models.IntegerField(blank=True, default=0, null=True)),
                ('leads', models.IntegerField(blank=True, default=0, null=True)),
                ('conversion_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('campaign_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user6', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Giveaway_Direct_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default='Course Giveaway Direct Registration', max_length=100, null=True)),
                ('visitors', models.IntegerField(blank=True, default=0, null=True)),
                ('leads', models.IntegerField(blank=True, default=0, null=True)),
                ('conversion_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('campaign_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user5', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoPayCardAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptopay_card_username', models.CharField(blank=True, max_length=100, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Direct_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default='Direct Registration', max_length=100, null=True)),
                ('visitors', models.IntegerField(blank=True, default=0, null=True)),
                ('leads', models.IntegerField(blank=True, default=0, null=True)),
                ('conversion_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('campaign_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GetResponseAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('getresponse_username', models.CharField(blank=True, max_length=100, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GetResponseAutoresponderAddContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaignId', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('api_key', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('isEnable', models.CharField(blank=True, default='enable', max_length=10, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='How_To_Set_Up_Your_BeTheMillionaire_System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default='How To Set Up Your BeTheMillionaire System', max_length=100, null=True)),
                ('visitors', models.IntegerField(blank=True, default=0, null=True)),
                ('leads', models.IntegerField(blank=True, default=0, null=True)),
                ('conversion_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('campaign_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user13', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndaCoinAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indacoin_username', models.CharField(blank=True, max_length=100, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Latest_Webinar_Replay_BTM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default='Latest Webinar Replay BTM', max_length=100, null=True)),
                ('visitors', models.IntegerField(blank=True, default=0, null=True)),
                ('leads', models.IntegerField(blank=True, default=0, null=True)),
                ('conversion_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('campaign_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user7', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerNanoSAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_nano_s_username', models.CharField(blank=True, max_length=100, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocalBitcoinsAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_bitcoins_username', models.CharField(blank=True, max_length=100, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membershiplevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, default=1, null=True)),
                ('name', models.CharField(blank=True, default='free', max_length=50, null=True)),
                ('package', models.CharField(blank=True, default='free', max_length=20, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mike_Hobbs_Usi_Tech_Team_Webinar_90_bitcoins_in_6_months',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default='Mike Hobbs Usi-Tech Team Webinar (90 bitcoins in 6 months)', max_length=100, null=True)),
                ('visitors', models.IntegerField(blank=True, default=0, null=True)),
                ('leads', models.IntegerField(blank=True, default=0, null=True)),
                ('conversion_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('campaign_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user12', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('payer_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_Token', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verify', models.CharField(default='pending', max_length=10)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Membershiplevel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preregistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpectroCoinCardAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spectrocoin_card_username', models.CharField(blank=True, max_length=100, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrezorSAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trezor_username', models.CharField(blank=True, max_length=100, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usi_Tech_7_Figure_Plan_In_2018',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default='Usi Tech 7 Figure Plan In 2018!', max_length=100, null=True)),
                ('visitors', models.IntegerField(blank=True, default=0, null=True)),
                ('leads', models.IntegerField(blank=True, default=0, null=True)),
                ('conversion_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user14', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usi_Tech_Btc_Packages_Calculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default='USI-TECH BTC-Packages Calculator', max_length=100, null=True)),
                ('visitors', models.IntegerField(blank=True, default=0, null=True)),
                ('leads', models.IntegerField(blank=True, default=0, null=True)),
                ('conversion_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('campaign_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user10', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usi_Tech_Direct_Funnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default='Usi-Tech Direct Funnel', max_length=100, null=True)),
                ('visitors', models.IntegerField(blank=True, default=0, null=True)),
                ('leads', models.IntegerField(blank=True, default=0, null=True)),
                ('conversion_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('campaign_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user9', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usi_Tech_Funnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default='Usi-Tech Funnel', max_length=100, null=True)),
                ('visitors', models.IntegerField(blank=True, default=0, null=True)),
                ('leads', models.IntegerField(blank=True, default=0, null=True)),
                ('conversion_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('campaign_link', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user8', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsiTechAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usi_username', models.CharField(blank=True, max_length=100, null=True)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='membership',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='membership_level', to='account.Membershiplevel'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referrals',
            field=models.ManyToManyField(blank=True, null=True, related_name='referral', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sponsor',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
