# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-31 21:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180401_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='membership',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_level', to='account.Membershiplevel'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='referrals',
            field=models.ManyToManyField(blank=True, related_name='referral', to=settings.AUTH_USER_MODEL),
        ),
    ]
