# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-12 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180401_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='package_buy_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
