# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-21 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_payment_expired_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_payments', to='account.Payment'),
        ),
    ]
