# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-27 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_referralsalecommission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('ipn_message', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
