# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-28 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_paypalconfirmation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paypalconfirmation',
            old_name='payer_ID',
            new_name='transactio_ID',
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
