# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-28 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20180429_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paypalconfirmation',
            old_name='transactio_ID',
            new_name='transaction_ID',
        ),
    ]
