# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-28 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20180429_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paypal_confirmation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.PaypalConfirmation'),
        ),
    ]
