# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-07 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20180429_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
