# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-10 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20180523_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='membership',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_level', to='account.Membershiplevel'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='payments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_payments', to='account.Payment'),
        ),
    ]
