# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-31 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(blank=True, max_length=255, null=True)),
                ('video_link', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
