# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-22 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_mul'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mul',
        ),
    ]
