# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-13 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_recentupdatepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentupdatepost',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recentupdatepost',
            name='post',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
