# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-15 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_livevideolinkupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livevideolinkupdate',
            name='link',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
