#!/bin/bash

NAME="bethemillionaire"
DIR=/home/mubarak/bethemillionaire
USER=mubarak
GROUP=mubarak
WORKERS=3
BIND=unix:/home/mubarak/run/gunicorn.sock
DJANGO_SETTINGS_MODULE=bethemillionaire.settings
DJANGO_WSGI_MODULE=bethemillionaire.wsgi
LOG_LEVEL=error

cd $DIR
source ../bin/activate

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

exec ../bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-



[program:bethemillionaire]
command=/home/mubarak/bin/gunicorn_start
user=mubarak
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/mubarak/logs/gunicorn-error.log









upstream app_server {
    server unix:/home/mubarak/run/gunicorn.sock fail_timeout=0;
}

server {
    listen 80;

    # add here the ip address of your server
    # or a domain pointing to that ip (like example.com or www.example.com)
    server_name 46.101.38.126;

    keepalive_timeout 5;
    client_max_body_size 4G;

    access_log /home/mubarak/logs/nginx-access.log;
    error_log /home/mubarak/logs/nginx-error.log;

    location /static/ {
        alias /home/mubarak/bethemillionaire/static/;
    }

    # checks for static file, if not found proxy to app
    location / {
        try_files $uri @proxy_to_app;
    }

    location @proxy_to_app {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_pass http://app_server;
    }
}





sudo ln -s /etc/nginx/sites-available/bethemillionaire /etc/nginx/sites-enabled/bethemillionaire
