from django.contrib import admin
from . import models

admin.site.register(models.UserProfile)
admin.site.register(models.Preregistration)

admin.site.register(models.BeTheMillionaire_3_Step_Registration_Funnel)
admin.site.register(models.Direct_Registration)
admin.site.register(models.Automated_Webinar_Funnel_Version_1)
admin.site.register(models.Automated_Webinar_Funnel_Version_2)
admin.site.register(models.Course_Giveaway_Direct_Registration)
admin.site.register(models.Course_Giveaway_3_Steps_Funnel)
admin.site.register(models.Latest_Webinar_Replay_BTM)
admin.site.register(models.Usi_Tech_Funnel)
admin.site.register(models.Usi_Tech_Direct_Funnel)
admin.site.register(models.Usi_Tech_Btc_Packages_Calculator)
admin.site.register(models.Bitconnect_Direct_Funnel)
admin.site.register(models.Mike_Hobbs_Usi_Tech_Team_Webinar_90_bitcoins_in_6_months)
admin.site.register(models.How_To_Set_Up_Your_BeTheMillionaire_System)
admin.site.register(models.Usi_Tech_7_Figure_Plan_In_2018)
admin.site.register(models.GetResponseAutoresponderAddContact)
admin.site.register(models.Membershiplevel)
admin.site.register(models.Payment)
admin.site.register(models.UsiTechAccount)
admin.site.register(models.BitconnectAccount)


admin.site.register(models.ClickMagicAccount)
admin.site.register(models.ClickFunnelsAccount)
admin.site.register(models.GetResponseAccount)
admin.site.register(models.AweberAccount)

admin.site.register(models.LedgerNanoSAccount)
admin.site.register(models.TrezorSAccount)
admin.site.register(models.CoinBaseAccount)
admin.site.register(models.SpectroCoinCardAccount)
admin.site.register(models.CryptoPayCardAccount)
admin.site.register(models.CexIOAccount)
admin.site.register(models.BitPandaAccount)
admin.site.register(models.LocalBitcoinsAccount)
admin.site.register(models.IndaCoinAccount)
admin.site.register(models.CoinMamaAccount)
admin.site.register(models.ITBAccount)
admin.site.register(models.ReferralSaleCommission)
