# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-15 14:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('member', models.ManyToManyField(blank=True, null=True, related_name='team_member', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
