# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-16 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180416_1909'),
        ('home', '0003_auto_20180416_0325'),
    ]

    operations = [
    ]
