# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-20 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180420_1834'),
        ('home', '0004_merge_20180416_2243'),
    ]

    operations = [
    ]
